Js in rails
EvgeniyBogd/TestGuru pull request #17
Opened 2022-11-16 16:49 UTC by EvgeniyBogd

2022-11-17 07:05 UTC, BubuntuClu requested changes

2022-11-17 07:05 UTC, BubuntuClu commented on app/javascript/utilities/check_password.js
> +    if (pass.value === passConfirm.value){
нужно еще учесть что поле подтверждения могут очистить и тогда все выделения тоже должны очиститься

2022-11-20 16:17 UTC, BubuntuClu commented on app/views/layouts/admin.html.erb
> +    <%= javascript_importmap_tags %>
эту штуку не надо менять. кажется ты начал идти куда-то не туда. у тебя вебпакер используется. что делает эта замена?

2022-11-28 16:50 UTC, EvgeniyBogd commented on app/views/layouts/admin.html.erb
> +    <%= javascript_importmap_tags %>
Так работает iportmap в 7-х рельсах

2022-11-28 16:51 UTC, merged